### PR TITLE
VUU80: Refactor Dialog styling to fix multiple components

### LINKED ISSUE #80: Fix styling on save layout panel
Some styling needs to be tweaked on the SaveLayoutPanel component to make it match the [Figma design](https://www.figma.com/file/MK8Nlh1RvMQrMySujl2FO1/VUU-Demo-App?node-id=725%3A38413&mode=dev).

1. Dialog title ("Save Layout") should be horizontally aligned with form field labels.
2. Border radius for top corners
3. Font style for placeholder text

Image

### PR DESCRIPTION
**Pull request by cfisher-scottlogic**
### Description
Closes #80

The `SaveLayoutPanel` styling has gradually become out of sync with the Figma design due to recent code refactorings. This PR addresses the specific `SaveLayoutPanel` issues by refactoring the generic `Dialog` component. I have tried to be as minimal as possible whilst still trying to make the CSS as globally applicable as possible for Dialog component consistency.

### Change List
- Add functionality in the `useDialog` hook to hide the 'close' icon on the Dialog header for `NewBasketPanel` and `SaveLayoutPanel` (to maintain consistency with Figma)
- Amend `DialogHeader` alignment and sizing for consistent positioning across usages and to fix the 'border-radius disappearing' issue
- Create a `vuuDialog-body` style class for global padding (as opposed to body-component padding)
- Change text colour of 'inputted' text in the `SaveLayoutPanel` form fields
- Fix Nunito-Sans incorrectly rendering as Times New Roman

#### **Save Layout Panel**
image
image

#### **New Basket Panel _(ignore the blue highlight)_**
image
image

#### **SimpleDialog**
image
image

### Notes
I have reviewed these changes against other usages of `Dialog` and `DialogHeader` (according to Webstorm) to ensure I'm not simply transferring dodgy rendering of Dialog to other areas of the application. @heswell as you're more familiar with the code, it would  be great if you could sanity check this. Also, let me know if you want me to re-add the close icon on the `NewBasketPanel`. The alignment of it is wrong across all usages of `DialogHeader` as far as I can see. The quick fix was to simply hide it rather than fix the alignment.

### CODE REVIEW

File: vuu-ui/packages/vuu-popups/src/dialog/useDialog.tsx [hunk 1]
```diff
@@ -22,6 +23,7 @@ export const useDialog = () => {
       onClose={handleClose}
       style={{ maxHeight: 500 }}
       title={dialogState.title}
+      hideCloseButton={dialogState.hideCloseButton || false}
```
Comment (vferraro-scottlogic) [inline vuu-ui/packages/vuu-popups/src/dialog/useDialog.tsx:26]: `|| false` here is redundant. hideCloseButton prop is optional in DIalogProps and Dialog has a default value (false) for it which will be used in case hideCloseButton props is left "undefined" hence here we can just pass dialogState.hideCloseButton to Dialog

File: vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.css [hunk 2]
```diff
@@ -8,16 +8,16 @@
 
 .vuuBasketNewBasketPanel-body {
     flex: 1 1 auto;
+    padding-top: 16px;
+    padding-bottom: 16px;
```
Comment (vferraro-scottlogic) [inline vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.css:12]:
```
    padding-top: 16px;
    padding-bottom: 16px
```
can be written in a single line as:
 `padding: 16px 0;`
I prefer the latter approach when we want the same padding for top/bottom or left/right to avoid repetition

File: vuu-ui/showcase/src/examples/Layout/SavePanel.examples.tsx [hunk 3]
```diff
@@ -14,7 +14,7 @@ export const SavePanel = () => {
       isOpen
       style={{ maxHeight: 500, borderColor: "#6d188b" }}
       title={"Save Layout"}
-      hideCloseButton
+      hideCloseButton={true}
```
Comment (vferraro-scottlogic) [inline vuu-ui/showcase/src/examples/Layout/SavePanel.examples.tsx:17]: `hideCloseButton={true}` is functionally equivalent to `hideCloseButton`. When a component prop is boolean and we want to pass true to it we can just have the property name without the `={true} ` see isOpen prop on the same component

File: vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.tsx [hunk 4]
```diff
@@ -76,7 +76,11 @@ export const NewBasketPanel = ({
     <Portal>
       <Popup anchorElement={{ current: document.body }} placement="center">
         <div {...htmlAttributes} className={cx(classBase, className)}>
-          <DialogHeader title="Add New Basket" onClose={onClose} />
+          <DialogHeader
+            title="Add New Basket"
+            onClose={onClose}
+            hideCloseButton={true}
```
Comment (vferraro-scottlogic) [inline vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.tsx:82]: this could also be just `hideCloseButton` without `={true}` (see other comment on hideCloseButton prop)

**Review by vferraro-scottlogic — CHANGES_REQUESTED** [review]
Looks good! Just a couple of comments around tidying up the code

File: vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.css (hunk 2 above)
Comment (cfisher-scottlogic) [reply vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.css]: [7cb928c](https://github.com/ScottLogic/finos-vuu/pull/100/commits/7cb928c1009535383fe3037472c354e893617aab)

File: vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.tsx (hunk 4 above)
Comment (cfisher-scottlogic) [reply vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.tsx]: [2a2dd2f](https://github.com/ScottLogic/finos-vuu/pull/100/commits/2a2dd2ff66595bf9dc891d45a9d49409c7f12bba)

File: vuu-ui/showcase/src/examples/Layout/SavePanel.examples.tsx (hunk 3 above)
Comment (cfisher-scottlogic) [reply vuu-ui/showcase/src/examples/Layout/SavePanel.examples.tsx]: [2a2dd2f](https://github.com/ScottLogic/finos-vuu/pull/100/commits/2a2dd2ff66595bf9dc891d45a9d49409c7f12bba)

File: vuu-ui/packages/vuu-popups/src/dialog/useDialog.tsx (hunk 1 above)
Comment (cfisher-scottlogic) [reply vuu-ui/packages/vuu-popups/src/dialog/useDialog.tsx]: [9c6279e](https://github.com/ScottLogic/finos-vuu/pull/100/commits/9c6279ec46c085e206b24978d40182fbee811a5f)

File: vuu-ui/packages/vuu-shell/src/layout-management/SaveLayoutPanel.css [hunk 5]
```diff
@@ -37,8 +36,8 @@
 }
 
 .saveLayoutPanel-inputText {
-  color: var(--light-text-secondary, #606477);
-  font-family: Nunito Sans Regular;
+  color: var(--light-text-primary, #15171B);
+  font-family: "Nunito Sans", sans-serif;
```
Comment (heswell) [inline vuu-ui/packages/vuu-shell/src/layout-management/SaveLayoutPanel.css:40]: shouldn't ever need font-family, it will be inherited

**Review by heswell — APPROVED** [review]
All looks good to me, happy to merge if you want to raise a PR on the finos repo

File: vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.css (hunk 2 above)
Comment (heswell) [reply vuu-ui/sample-apps/feature-basket-trading/src/new-basket-panel/NewBasketPanel.css]: me too

File: vuu-ui/packages/vuu-shell/src/layout-management/SaveLayoutPanel.css (hunk 5 above)
Comment (vferraro-scottlogic) [reply vuu-ui/packages/vuu-shell/src/layout-management/SaveLayoutPanel.css:40]: the font family for the input and the header don't match figmas: 
this change vs figma design
image
image

Comment (cfisher-scottlogic) [reply vuu-ui/packages/vuu-shell/src/layout-management/SaveLayoutPanel.css:40]: > shouldn't ever need font-family, it will be inherited

It looks like salt is overriding the font specified in vuu theme, so if I remove this Arial is rendered:

image

Comment (cfisher-scottlogic) [reply vuu-ui/packages/vuu-shell/src/layout-management/SaveLayoutPanel.css]: Fixed in [81fdd42](https://github.com/ScottLogic/finos-vuu/pull/100/commits/81fdd42172bfa22fb5a70589fc0fc3d024e5df62). 

Let me know if the comment for the `Nunito Sans A-Variant` `font-face` is clear enough - also whether the name is appropriate. It's weird that there's not a way of making this variant specifically use the `font-feature-settings` - we're having to specify this explicitly in each stylesheet to get the correct variant of the `font-face`.

Interestingly the `DialogHeader.css` needs to have the `--salt-text-fontFamily` variable modified to apply the correct font, as specifying `font-family` gets overriden:

_With `font-family`_
image

_With `--salt-text-fontFamily`_
image

Whereas `.saveLayoutPanel-inputText` in `SaveLayoutPanel.css` needs to have `font-family` and NOT `--salt-text-fontFamily`, as the latter doesn't do anything:

_With `--salt-text-fontFamily`_
image

_With `font-family`_
image

Not 100% sure what's going on here. Do you know of any other way where none of this is necessary @heswell?

**Review by vferraro-scottlogic — APPROVED** [review]
LGTM
